### ISSUE TITLE
Is it possible to add a palette for Aus states?

### ISSUE THREAD

**Issue by IdoBar** [ropenscilabs/ochRe#9]
See the attached image (from [Wikipedia](https://commons.wikimedia.org/wiki/File:Australia_States_Map_-_Colours_with_White_Borders.svg)):
![image](https://user-images.githubusercontent.com/16175388/167297786-f1a0b5cc-8407-4d5d-aade-d94766b6d14a.png)

You can use the following:
```
states_pal <- set_names(c("#741128", "#88CFEC", "#DBEBE7", "#C35E00", "#FFD800", "#0645AD", "#FF0000"), c("QLD", "NSW", "VIC", "NT",  "WA", "TAS", "SA"))
```

**Comment by dicook** [comment]
Hi @IdoBar Sorry, I just saw this now. Any chance you would be willing to make a pull request to add it? It would be a wonderful addition!

**Comment by IdoBar** [comment]
@dicook , done (see PR #10)   
Is it possible to use a named vector for the palette? will it break anything?
